### ISSUE TITLE
Build problem (caused by kryptology)

### ISSUE THREAD

**Issue by aeharvlee** [coinbase/rosetta-cli#291]
**Describe the bug**
When I try to build rosetta-cli from source, there is a build problem like below.
Please take a look.
```
go build ./...                                       
# github.com/coinbase/kryptology/pkg/core/curves/native/bls12-381
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/field_element.go:180:2: undefined: neg
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp.go:53:2: undefined: mul
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp.go:54:2: undefined: add
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp.go:98:2: undefined: mul
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp.go:102:2: undefined: mul
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp.go:109:3: undefined: mul
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp.go:110:3: undefined: mul
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp.go:123:2: undefined: square
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp2.go:75:2: undefined: add
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp2.go:76:2: undefined: add
../../../go/pkg/mod/github.com/coinbase/kryptology@v1.5.5/pkg/core/curves/native/bls12-381/fp2.go:76:2: too many errors
```

**To Reproduce**
1. git clone this project
2. run `make build` or `make deps` or `make install` .

**Expected behavior**
Must be build successfully.

**Additional context**
* OS: macOS 12.3
* Go version: `go1.17.7 darwin/arm64`
* Source code version of rosetta-cli: https://github.com/coinbase/rosetta-cli/commit/18013bd2628aa98d9cde87e5d10b3216c35d070c

BTW, Build on Latest tag v0.7.3 works

**Comment by shrimalmadhur** [comment]
Hello @aeharvlee - I just merged the fix in https://github.com/coinbase/rosetta-cli/pull/284 - this should help you build from from source. Let me know if that doesn't work.

**Comment by aeharvlee** [comment]
@shrimalmadhur 

I checked it and building is done successfully  :)
Thanks for your response.
